### ISSUE TITLE
[Corrigir erro EXTREMO]

### ISSUE THREAD

**Issue by marcelobiao** [Keader/PBL-Compiladores#2]
Só para zoar 3huh3uh3uhu3hu3hu3huh3uh3uh3urbbrbr
![hue](https://cloud.githubusercontent.com/assets/8891971/17266848/e99a9246-55d3-11e6-8316-248017b2ad21.png)

**Comment by Keader** [comment]
@AlbertoJunior esse é com você fera :+1:

**Comment by AlbertoJunior** [comment]
Sabe que não to entendendo porra nenhuma né? :v
